version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: flood_postgres
    environment:
      POSTGRES_DB: flood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init_postgis.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
